name = "willywotz"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-31"

[build]
command = "curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env && cargo install -q worker-build && worker-build --release"