name = "willywotz"
main = "build/index.js"
compatibility_date = "2026-06-01"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
